### ISSUE TITLE
Hall of the Elders softlock

### ISSUE THREAD

**Issue by tomlube** [AxioDL/metaforce#407]
https://www.youtube.com/watch?v=CThKSxPrvfA

Currently the only softlock preventing the game from being beaten, as far as I know. Does not appear to have any direct workarounds (you can just avoid this path, though)

**Comment by tomlube** [comment]
There is a hack that fixes this currently but it still needs to properly be debugged

**Comment by shiiion** [comment]
Caused by two things:

1. Locator for the ball "bone" (Ball_SDK) in the chozo statue skeleton is reading out incorrect transforms during the throw animation. Not sure if this is due to incorrect computation of the transform, or incorrect cooked skeleton/animation data from hecl.
2. The collision primitive for the rotating bowling tube thing (Platform_BowlingBridge, BBD81465.DCLN) cooked by hecl seems to be incorrect, as swapping in the original retail version results in nearly perfect matches for position/velocity compared to retail.

**Comment by tomlube** [comment]
Fixed on new-cmodel.
